---
title: "Format Check (delete me)"
author: "Bill Prisbrey"
date: "2025-06-27"
output: html_document
---

I am simply making sure my formatting of the meeting notes is correct.  

This report will be deleted, and these notes will appear in "Workforce Journey Exploratory Data Analysis -- Initial"


Of particular interest are the so-called "boundary actions" that define entry and exit into the workforce.  These include "primary" actions like hiring and retiring; "break" actions that describe a "short work break"; and "leave" actions for long term disability or a paid leave of absence.   

When these boundary actions are so simply defined, there are inconsistencies in the respective tallies.  These need to be clarified with HR.

Possible improvements and points for additional clarity include:    

  * Anchor the age bands to a specific date rather than the time of the query.   
  * Clarify the actions and reasons that define boundary entry and exits.   
  * Clarify the fields "EMPL_RCD" and "EFFSEQ".   
  * Clarify edge cases and complex cases (like the employment history of "00028073" and the records of “00029479” on EFFDT == “2011-07-16”).  
  * Review the definition of "voluntary" vs "involuntary" termination and discuss specific cases.   

***MEETING NOTES, 6.27.2025:***   
This report was reviewed with HR and the following are the meeting notes.   

*PEOPLE:*  Brian Gelsinger, Daniel Hinojosa, Dave Howell, Greg Francom, Kaidon Spencer, Bill Prisbrey

*ACTION ITEMS:*   

* Brian/Daniel to modify the query:   
	* Define the age band according to the EFFDT, not the time of the query    
	* Add fields for the job code, the job description, and the department    
	* Add a flag for when a transfer (XFR) is a change in job code only (defined as a change from a four digit code to a six digit code)    
* Bill to re-work the analysis with the clarifications and updated information
 
*SUMMARY:*    

**Age band:** 

  * Can the age band be calculated at a set time, or at the time of the EFFDT instead of at the time of query? --> Yes, can modify the query to do that.    

**Employee records:**   

  * Employee records identify concurrent positions.  They should each have their own complete set of job actions (such as rehire (REH) and terminate (TER).)  The employee records starts at 0 where 1 is the first concurrent job.  If the employee exits job/employee record 0, then employee record 1 continues. If the employee starts another concurrent position, then this second position will be added as employee record 0 again.  Concurrent positions are added at the lowest employee record available.  Because they are not unique identifiers, HR will add the job code, job description, and department.    
  
  * Some actions will apply across all jobs/employee records, causing the apparent duplication.  For example, a "leave" would apply to  both concurrent positions.   
  

**Effective Sequence:**   

  * This applies if multiple actions occur on the same date.  It is the order that the actions are applied.    

**Boundary actions:**   

  * If a "leave" action (LOA, PLA) has the reason "EXT" then it shouldn't be counted as another exit, because it's an extension.
  * Long-term disability (LTO) should be an exit.

**Extreme cases:**  

  * Some departments would add employee records as a way of managing pay distribution, and it doesn't mean a concurrent job or a different job.  This practice should be much less after 2013.  
  

**New job codes:**    

  * There is a slow movement from the old job codes (four digit) to the new job codes (six digits.)  These happen with action TRANSFER (XFR) and we can flag these for those reasons.    

**Voluntary vs involuntary termination:**  

  * To be discussed at a later date.    

**Other:**    

  * A "break" is for a non-benefit employee where a "leave" is for a benefited employee.   
  
  * Some of the inconsistencies in exit/entries are due to people entering before the start of the query. --> Bill: I am aware, and should have clarified that in the report.     
  
  * The data is much more consistent, accurate, and complete after 2013.    
  
  * The transition to PeopleSoft started in 2009.  People employed during the transition had their work history transported to PeopleSoft.  But if they weren't employed during the transition, and were re-hired later, their employment history was lost.   

