---
title: "Business Framing for Exploring Investigator Turnover"
author: "Bill Prisbrey"
date: "2025-04-15"
output: 
  html_document:
    keep_md: TRUE
---

**PURPOSE:**  This document creates the initial business framing describing an investigation into turnover by principal investigators.  This is a living document and may be continuously updated with feedback and new information.   

**PROBLEM STATEMENT:** ***Can the University of Utah improve research spending by improving retention of high performing and high potential researchers?***

Management is concerned that principal investigators (PIs) who secure large grants or receive substantial funding may be leaving the organization at higher rates than their peers, possibly due to targeted recruitment by other institutions.

An investigation of researcher turnover and its drivers may inform changes of retention policies and practices.   

**BACKGROUND:**     
In order to achieve Dr. Taylor Randall's objective to increase research spending to a $1 B milestone, the Vice President for Research wishes to explore improving retention of high-performing principal investigators.  The Office of Sponsosred Projects has found that a disproportionately small percentage of investigators are responsible for the majority of research funds (consistent with the Pareto principle, where 20% of the population are responsible for 80% of the results.) The Office wonders if the high-performing few are experiencing high turn-over due to being poached or are departing for other institutions, and what the drivers and mitigators of turnover are.

**HISTORY:**      
On 13 February 2025, Bill Prisbrey presented his Powerpoint slides titled "Grants Exploratory Phase I Winning 7b" to Dr. Erin Rothwell and others.  His section describing win rates by principal investigator characteristics elicited several questions on whether we can identify "low" and "high" performing investigators; how we can support them better; and whether we are retaining our top performers.

**STAKEHOLDERS:**   

- *Dr. Erin Rothwell*   
  As the Vice President for Research, Dr. Rothwell heads the Office of Sponsored Projects and is the sponsor of this analysis project.   
  
  Her primary objective is accelerating the University of Utah's accomplishment of the $1 B milestone through improved retention of top-performing principal investigators.    
  
  She is limited in her ability to directly affect retention and turn-over, as she does not sit on tenure committees nor is consulted in faculty hiring decisions.  However, she can affect policy by making recommendations to President Randall. 
  
- *Deans of the colleges*    
  Deans of the colleges directly affect recruitment and retention policies and decisions.  They have various distinct priorities and unique criteria from one another, and their current policies and objectives are unknown to this author at this time.
  
- *Tenure committees*   
  Tenure committees consist of faculty who decide which faculty are awarded tenure.  Similar to the deans of the various colleges, they have distinct priorities and unique criteria from one another, and their current policies and objectives are unknown to this author at this time.
  
- *Human Resources*    
  University HR will have knowledge of objectives, criteria, and policies for recruitment and retention.  They may be a key partner in implementing any suggested changes.  
  
  Analysts at HR may have already conducted turnover analyses by college and department. 

- *Team members*
    - David Howell  
  As the Associate Director of Research Analytics and Data, Mr. Howell will be the primary contact for this analysis project.
    - Greg Francom  
  As Business Analyst in Research Analytics and Data, Mr. Francom will assist in developing the report through advising progress and providing feedback.

**COMMUNICATION PLANNING:**     
The study findings will be provided to Dr. Rothwell, who will share with and include other parties and individuals at her discretion. 

**MANAGEMENT OF NEGATIVE OUTCOMES AND PERSPECTIVES:**   
To be determined.

**AMENABILITY TO ANALYTICS:**     
Identification and analysis of high performer turnover by the Office of Sponsored Projects is amenable to analytics.    

Although data and methodologies are available, actionability could be improved with a more detailed plan to use this information. 

**Amenability components:**   
  
  - *Data availability*  
    - 28,790 proposals over ten years by 2,936 principal investigators from Grants Exploratory (Phase I.)
    - HR data describing employment terms
    - Funding spent [not yet analyzed]
    - Faculty activity database called "Elements" describing performance data (such as class load, committee service, conference presentations, publications, and patent applications.)
    - External database "Dimensions" on researcher activity

  - *Methodology selection*  
  Employee turn-over is a standard HR metric that is readily calculated and reasonably compared across groups using chi-squared, ANOVA, and Kruskal-Wallis methods.  More advanced methods to predict and describe turnover include logistic regression, decisions trees, and survival models.
  
  - *Actionability*        
  Dr. Rothwell could use this information to develop and recommend a strategy to senior leadership that improves retention of high-performing and high-potential principal investigators.    

**COSTS AND BENEFITS:**    
  Because research at the U follows the Pareto principle, improved retention of top researchers should have a disproportionate effect on research spending.   
  
  This study could help clarify whether this is a problem, the size of the problem, and how much spending could be increased with improved retention.    

**RISKS:**    
  An analysis of historical data carries the inherent assumption that the future will continue as the past.  However, the university faces a historical discontinuity in how federal funding is awarded and administered. 
  Despite this discontinuity and uncertainity, it is suggested that a better understanding of past behavior will optimally inform current decisions.  

**NEXT STEPS:** 

- Refine this document based on feedback.   
- Conduct analytical framing.   

