---
title: "Project Issue (Slow computation)"
author: "Bill Prisbrey"
date: "2025-08-25"
output:
  html_document:
    keep_md: true
---

***STATUS:***  Remedies under investigation

***ISSUE NAME:***  Slow computation   

***ISSUE ID:*** 004   

***DATE IDENTIFIED:***  20 August 2025    

***DESCRIPTION:***  

Previously Bill Prisbrey had access to enterprise Posit software that ran on a server, called Workbench.  However, that license was allowed to expire, forcing all work to move to Bill's laptop.    

The laptop runs much slower than the server.  Some benchmark speeds are twenty times slower.  A report on the server took 3.5min, while the same report took 1.9 hours on the laptop.

***IMPACT LEVEL:***   

  High.  This delays project completion.    

***PROJECT IMPACT:***   

  A much slower computational speed will delay progress.    
  
***ASSIGNED TO:*** Luis Oquendo      

***ACTION PLAN OR RESOLUTION STRATEGY:***     

Remedies and alternatives are under investigation.    

Possibilities include:    

  (1) Replacement laptop    
  (2) Re-formatting or re-configuration of current laptop   
  (3) Renewal of Posit enterprise license ($5,538)    
  (4) Dedicated VMware instance on a server   
  
  
***LOG:***    

*8 August 2025:*  A benchmark script comparing Workbench and laptop showed the laptop was twenty times slower on some tests.   
*21 August 2025:*  A report took 3.5min to run on Workbench and 1.9 hours on the laptop.    

*23 Augsut 2025:* Posit Workbench enterprise license expired.    


